import type { Metadata } from 'next';
import { Geist, Geist_Mono, Poiret_One } from 'next/font/google';
import './globals.css';
import { UserProvider } from '@/contexts/userContext';

import Footer from '@/components/Footer';
import Navigation from '@/components/Navigation';
import { CategoryProvider } from '@/contexts/categoryContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
});

const poiretOne = Poiret_One({
  variable: '--font-poiret-one',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poiretOne.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col w-full">
        <UserProvider>
          <CategoryProvider>
            <Navigation isOnFooter={true} />
            <div className="flex flex-1 flex-col">{children}</div>
            <Footer />
          </CategoryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
